# Generated by Django 5.2.8 on 2025-12-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contactinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='purchase_price',
            new_name='price',
        ),
    ]
